# Generated by Django 5.1.5 on 2026-04-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('doctor', 'Doctor')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
